version = 0.1

[default.global.parameters]
region = "us-east-1"

[dev.deploy.parameters]
stack_name = "mealnexus-dev"
resolve_s3 = true
s3_prefix = "mealnexus-dev"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev DomainName="

[prod.deploy.parameters]
stack_name = "mealnexus-prod"
resolve_s3 = true
s3_prefix = "mealnexus-prod"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod DomainName=mealnexus.me"
